import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { Banknote, House, Menu, RotateCcw, Volume2, Wallet, PiggyBank, ArrowRight, Dice5, Sparkles, Flag, X } from 'lucide-react';
import { applyAction, createMission, description, financialTotals, options, shouldRestoreStoredMission, validSave, type Mission } from '../../packages/money-quest/engine';
import { boardStopInfo } from './board-stop-info';
import { goals, lessonBeats, quarterNames, wordBank } from '../../packages/money-quest/content';
import { boardNames, mascots } from '../../packages/curriculum';
import { missionReport } from '../../packages/learning-report';
import { BoardWorld, CharacterPortrait } from './World';
import { advanceWalkElapsed, sampleRoll, type RollEvent } from './board-presentation';
import { latestMissionDie, missionAnimations, missionOutcomeTotals } from './mission-turn-presentation';
import { MissionDice } from './learning/MissionDice';
import { useGame } from './store';
import { BoardConversation, ChoiceReplies, OutcomeChat } from './learning/BoardConversation';
import { LessonLab } from './learning/LessonLab';
import { LearningReportView } from './learning/LearningReports';
import './quest-mission.css';
import './mission-play.css';

const SAVE='lead-money-quest-v03-local';
function load():Mission|null {try{const g=JSON.parse(localStorage.getItem(SAVE)||'null');return validSave(g)?g:null;}catch{return null;}}
const brief=(text:string)=>text.split(/(?<=[.!?])\s+/).slice(0,2).join(' ');
function Brand(){return <a href="/" className="play-brand" aria-label="LEAD Money Quest home"><span><i>L.</i><i>E.</i><i>A.</i><i>D.</i></span><small>MONEY QUEST</small></a>;}
function signed(value:number){return `${value>0?'+':''}${value}`;}
function Reason({label,value,onChange,choices}:{label:string;value:string;onChange:(s:string)=>void;choices:string[]}){return <fieldset className="play-reason"><legend>{label}</legend><div>{choices.map(choice=><button key={choice} type="button" aria-pressed={value===choice} onClick={()=>onChange(choice)}>{choice}</button>)}</div><details><summary>Say it in my own words</summary><textarea aria-label={label} maxLength={500} value={value} onChange={e=>onChange(e.target.value)} placeholder="A short thought is enough."/></details></fieldset>;}

export default function MissionPlay(){
  const [g,setGame]=useState<Mission|null>(load),[avatar,setAvatar]=useState('lido'),[length,setLength]=useState<2|4>(4),[consent,setConsent]=useState(false);
  const [error,setError]=useState(''),[storageError,setStorageError]=useState(false),[info,setInfo]=useState(''),[inspected,setInspected]=useState(0);
  const [ready,setReady]=useState(false),[textBoard,setTextBoard]=useState(false),[roll,setRoll]=useState<RollEvent|null>(null),[elapsed,setElapsed]=useState(0),[voice,setVoice]=useState(false),[quizReady,setQuizReady]=useState(false);
  const reduced=useGame(s=>s.reduced),toggleMotion=useGame(s=>s.toggleMotion);
  const [why,setWhy]=useState(''),[next,setNext]=useState(''),[price,setPrice]=useState(6),[goal,setGoal]=useState(goals[3]);
  const [helper,setHelper]=useState('none'),[upgrade,setUpgrade]=useState(false),[save,setSave]=useState(0),[stock,setStock]=useState(0),[reinvest,setReinvest]=useState(false),[readiness,setReadiness]=useState([false,false,false]),[recoveryAnswer,setRecoveryAnswer]=useState<number|null>(null);
  const current=useRef(g),lock=useRef(false),animating=useRef(false),animationQueue=useRef<RollEvent[]>([]),walkElapsed=useRef(0),panel=useRef<HTMLDivElement>(null),menu=useRef<HTMLDetailsElement>(null);current.current=g;
  const sample=sampleRoll(roll,elapsed,g?.position||0,reduced||textBoard),busy=!sample.complete;
  const investment=g?[...g.events].reverse().find(event=>event.type==='investment-result'&&event.quarter===g.quarter&&event.turn===g.turn):undefined;
  const lastDie=latestMissionDie(g),dieValue=roll?.value??(g?.phase==='board'?g.lastDie:lastDie.value),dieChance=roll?.replacement??(g?.phase==='board'?false:lastDie.chance);
  const rollCount=g?.events.filter(event=>event.type==='die'&&event.data.purpose==='movement').length||0;
  const outcomeTotals=useMemo(()=>missionOutcomeTotals(g),[g]);
  function clearAnimation(){animationQueue.current=[];animating.current=false;setRoll(null);}
  function send(type:string,data:Record<string,unknown>={}){
    if(lock.current||animating.current||busy||!current.current)return;
    if(type==='roll-dice'&&!ready&&!textBoard)return;
    lock.current=true;
    try{
      const other=load();
      if(other&&shouldRestoreStoredMission(current.current,other)){current.current=other;setGame(other);clearAnimation();setInfo('');setError('Your latest mission from another tab is restored. Review your choice before continuing.');return;}
      const old=current.current,result=applyAction(old,{id:crypto.randomUUID(),type,...data});
      const animations=missionAnimations(old,result,performance.now());
      if(animations.length&&!reduced&&!textBoard){
        walkElapsed.current=0;
        animating.current=true;animationQueue.current=animations.slice(1);
        setRoll(animations[0]);setElapsed(0);
      }
      current.current=result;setGame(result);setError('');
    }catch(e){setError((e as Error).message);}finally{lock.current=false;}
  }
  useEffect(()=>{if(!g)return;try{localStorage.setItem(SAVE,JSON.stringify(g));setStorageError(false);}catch{setStorageError(true);}},[g]);
  useEffect(()=>{
    if(!roll)return;
    if(reduced||textBoard){clearAnimation();return;}
    let frame=0,previous:number|null=null;
    const resetFrame=()=>{previous=null;};
    const tick=(now:number)=>{
      if(ready&&!document.hidden){
        walkElapsed.current=advanceWalkElapsed(walkElapsed.current,previous===null?0:now-previous);
        previous=now;setElapsed(walkElapsed.current);
      }else previous=null;
      if(sampleRoll(roll,walkElapsed.current,current.current?.position||0).complete){
        const nextAnimation=animationQueue.current.shift();
        if(nextAnimation){walkElapsed.current=0;setElapsed(0);setRoll(nextAnimation);}
        else {animating.current=false;setRoll(null);}
      }
      else frame=requestAnimationFrame(tick);
    };
    document.addEventListener('visibilitychange',resetFrame);
    frame=requestAnimationFrame(tick);
    return()=>{cancelAnimationFrame(frame);document.removeEventListener('visibilitychange',resetFrame);};
  },[roll,reduced,textBoard,ready]);
  useEffect(()=>{setWhy('');setNext('');setPrice(g?.price||6);setGoal(g?.goal||goals[3]);setHelper(g?.helper.hired?(g.helper.benefit?'benefit':'helper'):'none');setUpgrade(false);setSave(0);setStock(0);setReinvest(false);setReadiness([false,false,false]);setRecoveryAnswer(null);setQuizReady(false);},[g?.id,g?.started,g?.phase,g?.quarter,g?.lesson.step]);
  useEffect(()=>{if(!busy)panel.current?.focus({preventScroll:true});},[busy,g?.phase,g?.lesson.step,info]);
  function openInfo(which:string){menu.current?.removeAttribute('open');setInfo(which);if(['ledger','word-bank','sparko'].includes(which))send('evidence',{panel:which});}
  function inspect(index:number){if(busy)return;setInspected(index);setInfo('guide');}
  const beat=g&&g.phase==='lesson'?lessonBeats(g.quarter,g.lesson.depth)[g.lesson.step]:null;
  let title='Where will you land?',guide='Roll the dice, explore the village, then choose what happens at your stall.';
  if(g){
    if(beat){title=beat.title;guide=g.lesson.answered?g.lesson.feedback:beat.text;}
    else if(busy){title=sample.rolling?(sample.dieProgress<1?'Give it a tumble!':`You rolled ${dieValue}!`):roll?.replacement?'Your chance result':`Next stop: ${boardNames[g.position]}`;guide=roll?.replacement?'This roll settles your choice. Your character stays on this space.':sample.rolling?(sample.dieProgress<1?'One roll, one adventure. Watch for your number!':'Your number is ready. Here we go!'):g.position===0?'You made it around the village! Save your learning before the next lap.':'Follow your character to the next stop. Your decision will appear when you arrive.';}
    else if(g.phase==='deposit'){title='Five coins for your new idea';guide='You finished this lesson. Bring your five practice coins to the village and try a business choice.';}
    else if(g.phase==='banner'){title=quarterNames[g.quarter-1];guide='Roll, explore, and try your ideas. A new surprise waits around every corner.';}
    else if(g.phase==='offers'){title='What is your plan?';guide='Keep enough coins for surprises. Pick the tools that fit your goal for this lap.';}
    else if(g.phase==='decision'){const d=description(g);title=d[0];guide=brief(d[1]);}
    else if(g.phase==='outcome'){title=g.outcome?.title||'Your choice made a difference';guide=brief(g.outcome?.text||'');}
    else if(g.phase==='reflection'){title=`Lap ${g.quarter} complete!`;guide='Look at what changed because of your choices. What would you keep or try differently?';}
    else if(g.phase==='recovery'||(g.phase==='board'&&g.wallet===0)){title='Let’s make a fresh plan';guide='An empty wallet is a chance to rethink, not the end of the game. Your savings stay safe.';}
    else if(g.phase==='settlement'||g.phase==='done'){title=g.phase==='done'?'A founder who keeps learning':'Look how far you came';guide='You tried ideas and noticed their results. Your next good idea can start with what you learned today.';}
    if(info==='guide'){const m=boardStopInfo(g,inspected);title=`${inspected} · ${boardNames[inspected]}`;guide=m.guide;}
    if(info==='ledger'){title='Where did your coins go?';guide='Money coming in and money going out tell different parts of the story. Here are your latest entries.';}
    if(info==='word-bank'){title='A word with Sparko';guide='Every money word describes something you can notice in your stall. Pick one idea to try next.';}
    if(info==='lab'){title='Try it with practice coins';guide='Explore an example here while your board waits. These example coins never change your mission wallet.';}
    if(info==='sparko'){title='Think it through with Sparko';guide='What is your goal, and which costs or customer budgets matter for this choice? I can explain an idea; the decision belongs to you.';}
  }
  useEffect(()=>{if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();if(voice&&g){const speech=new SpeechSynthesisUtterance(`${title}. ${guide}`);speech.lang='en-US';speech.rate=.92;window.speechSynthesis.speak(speech);}return()=>window.speechSynthesis.cancel();},[voice,title,guide]);
  function menuPrice(full=false){return <label className="play-range">Menu price <strong>{price} coins</strong><input aria-label="Menu price" type="range" min={full?4:Math.max(4,(g?.price||6)-1)} max={full?8:Math.min(8,(g?.price||6)+1)} value={price} onChange={e=>setPrice(+e.target.value)}/></label>;}
  function restart(){try{localStorage.removeItem(SAVE);}catch{setStorageError(true);}setGame(null);clearAnimation();setConsent(false);setInfo('');}
  function replies(options:{id:string;label:string;detail?:string;reason?:string;disabled?:boolean}[],onChoose:(id:string,reason:string)=>void){return <ChoiceReplies key={[g?.id,g?.started,g?.quarter,g?.turn,g?.phase].join(":")} options={options} onChoose={onChoose} disabled={busy}/>;}
  function recovery(game:Mission){const b=lessonBeats(game.quarter,'review')[0];return <><Reason label="My recovery plan" value={why} onChange={setWhy} choices={['I will keep a buffer for surprises.','I will compare my price and costs.']}/><p className="play-small-question">{b.question}</p><div className="play-tap-options">{b.choices.map((c,i)=><button key={c} aria-pressed={recoveryAnswer===i} onClick={()=>setRecoveryAnswer(i)}>{c}</button>)}</div>{recoveryAnswer!==null&&<p className="play-feedback">{b.explanation}</p>}<button className="play-primary" disabled={why.length<3||recoveryAnswer===null} onClick={()=>send('recover',{choice:'learning',reason:why,answer:recoveryAnswer})}>Try again with 3 learning coins</button><button className="play-quiet" disabled={why.length<3} onClick={()=>send('recover',{choice:'advance',reason:why})}>Borrow 5 coins · repay at the finish</button></>;}
  function content(game:Mission):ReactNode{
    if(info)return <>{info==='lab'?<LessonLab quarter={game.quarter} step={game.quarter===2&&game.lesson.depth==='review'&&game.lesson.step===1?2:game.lesson.step} price={price} reduced={reduced}/>:info==='word-bank'?<dl className="play-word-bank">{wordBank.map(([word,meaning])=><div key={word}><dt>{word}</dt><dd>{meaning}</dd></div>)}</dl>:info==='ledger'?<ol className="play-ledger">{game.ledger.slice(-10).reverse().map(e=><li key={e.id}><span>{e.note}</span><strong>{signed(e.wallet)} wallet{e.savings?` · ${signed(e.savings)} saved`:''}</strong></li>)}</ol>:info==='guide'?<><nav className="play-space-picker" aria-label="Explore board spaces">{boardNames.map((name,i)=><button key={i} aria-label={`Space ${i}: ${name}`} aria-pressed={inspected===i} onClick={()=>setInspected(i)}>{i}</button>)}</nav><p className="play-note">{boardStopInfo(game,inspected).title}</p><ul className="play-guide-choices">{boardStopInfo(game,inspected).options.map(text=><li key={text}>{text}</li>)}</ul></>:<div className="play-tap-options"><button onClick={()=>openInfo('word-bank')}>Explain a money word</button><button onClick={()=>openInfo('lab')}>Try with practice coins</button><button onClick={()=>openInfo('ledger')}>Look at my latest coins</button></div>}<button className="play-primary" onClick={()=>setInfo('')}>Back to my game <ArrowRight size={16}/></button></>;
    if(busy)return roll?.kind==='walk'?<div className="play-walking" role="status"><span className="play-walking-dots" aria-hidden="true"><i/><i/><i/></span><p>Continuing to {boardNames[game.position]}…</p><small>Using the remaining steps from your previous roll.</small></div>:<MissionDice value={dieValue} progress={sample.dieProgress} rollId={roll?.id} rolling={sample.rolling} busy={busy} canRoll={false} onRoll={()=>{}} chance={dieChance} destination={boardNames[game.position]} remaining={roll?Math.max(0,roll.path.length-(sample.tile===roll.from?0:roll.path.indexOf(sample.tile)+1)):0} rollCount={rollCount}/>;
    if(game.phase==='lesson'&&beat){const last=game.lesson.step===lessonBeats(game.quarter,game.lesson.depth).length-1;return <><span className="play-mini-label">IDEA {game.lesson.step+1} / {lessonBeats(game.quarter,game.lesson.depth).length}</span>{!game.lesson.answered?quizReady?<><div className="play-example">{beat.example}</div><h3 className="play-small-question">{beat.question}</h3><div className="play-tap-options">{beat.choices.map((c,i)=><button key={c} onClick={()=>send('answer',{answer:i})}>{c}</button>)}</div></>:<><div className="play-example">{beat.example}</div><p className="play-note">Read Sparko’s lesson and example first. Then try one quick question.</p><button className="play-primary" onClick={()=>setQuizReady(true)}>Start the quick quiz <ArrowRight size={16}/></button></>:last?<>{game.quarter===1&&<>{menuPrice(true)}<label className="play-field">My business goal<select value={goal} onChange={e=>setGoal(e.target.value)}>{goals.map(v=><option key={v}>{v}</option>)}</select></label></>}{game.quarter===4&&<fieldset className="play-checks"><legend>Ready for the next choice?</legend>{['I know my goal.','I kept room for unexpected costs.','I considered a possible loss.'].map((v,i)=><label key={v}><input type="checkbox" checked={readiness[i]} onChange={e=>setReadiness(readiness.map((old,j)=>i===j?e.target.checked:old))}/>{v}</label>)}</fieldset>}<Reason label="What will I try?" value={why} onChange={setWhy} choices={['I will compare the price with my costs.','I will keep some coins for surprises.','I will notice what my customers need.']}/><button className="play-primary" disabled={why.length<3||(game.quarter===4&&!readiness.every(Boolean))} onClick={()=>send('lesson-next',{reason:why,price,goal,ready:readiness.every(Boolean)})}>Complete this lesson</button></>:<button className="play-primary" onClick={()=>send('lesson-next')}>Continue learning <ArrowRight size={16}/></button>}<button className="play-quiet" onClick={()=>openInfo('lab')}>Try with practice coins</button></>;}
    if(game.phase==='deposit')return <><div className="play-coin-award"><Banknote/>+5 <small>learning coins</small></div><button className="play-primary" onClick={()=>send('deposit')}>Bring my coins to the board</button></>;
    if(game.phase==='banner')return <><p className="play-route-explainer"><span>Roll</span><ArrowRight/><span>Explore</span><ArrowRight/><span>Choose</span></p><button className="play-primary" onClick={()=>send('banner')}>{game.quarter===1?'Let’s roll!':'Plan my next lap'}</button></>;
    if(game.phase==='offers')return <>{menuPrice()}{!game.upgrade&&<label className="play-check"><input type="checkbox" checked={upgrade} onChange={e=>setUpgrade(e.target.checked)}/>Grow the stall · 5 coins · +1 customer budgets</label>}{game.quarter>=3&&<label className="play-field">My team<select value={helper} onChange={e=>setHelper(e.target.value)}><option value="none">Work on my own</option><option value="helper">Hire · 1 coin per Sales Day worked</option><option value="benefit">Hire with reliability · {game.helper.benefit?'already paid':'2 coins once'} + wages</option></select></label>}{game.quarter===4&&<details className="play-allocation" open><summary>Set aside up to 5 coins</summary><label className="play-field">Save<input aria-label="Save allocation" type="number" min={0} max={5} value={save} onChange={e=>setSave(+e.target.value)}/></label><label className="play-check"><input type="checkbox" checked={reinvest} onChange={e=>setReinvest(e.target.checked)}/>Reinvest 3 · +1 customer budgets</label><label className="play-field">Stock stake<input aria-label="Stock stake" type="number" min={0} max={3} value={stock} onChange={e=>setStock(+e.target.value)}/></label><p>Stock can lose the stake, return it, or double it. Savings stay protected.</p><b>{save+stock+(reinvest?3:0)} / 5 coins allocated</b></details>}<Reason label="My plan because…" value={why} onChange={setWhy} choices={['I want a buffer for unexpected costs.','I want to serve more customers.','I checked what my wallet can afford.']}/><button className="play-primary" disabled={why.length<3} onClick={()=>send('offers',{reason:why,price,helper,upgrade,save,stock,reinvest})}>Try this plan</button></>;
    if(game.phase==='board'){

      return <>{game.wallet===0?recovery(game):<><MissionDice value={game.lastDie} rolling={false} busy={false} canRoll={ready||textBoard} onRoll={()=>send('roll-dice',{turn:game.turn})} rollCount={rollCount}/>{!ready&&!textBoard&&<p role="status" className="play-note">Opening the village… You can use the text board while it loads.</p>}<p className="play-choice-hint">Roll 1–6 spaces. Make your choice when you land.</p></>}</>;
    }
    if(game.phase==='decision')return replies(options(game),(choice,reason)=>send('choose',{choice,reason}));
    if(game.phase==='outcome'&&game.outcome)return <><OutcomeChat outcome={outcomeTotals&&game.outcome.profit!==undefined?{...game.outcome,...outcomeTotals.finance}:game.outcome} liabilityTotal={game.liability} showText={false} {...outcomeTotals} price={game.price}/>{game.outcome.die&&<p className="play-note">Chance result: {game.outcome.die}. Your pawn stays here.</p>}{game.revision&&<details className="play-allocation"><summary>Keep or revise my price</summary>{replies([{id:'keep',label:`Keep ${game.price}`},{id:'lower',label:`Try ${Math.max(4,game.price-1)}`},{id:'raise',label:`Try ${Math.min(8,game.price+1)}`}],(choice,reason)=>send('revise',{price:choice==='keep'?game.price:choice==='lower'?Math.max(4,game.price-1):Math.min(8,game.price+1),reason}))}</details>}</>;
    if(game.phase==='reflection')return <><Reason label="What did I notice?" value={why} onChange={setWhy} choices={['More customers did not always mean more profit.','Saving kept some coins for later.','I needed to count every cost.']}/><Reason label="What will I try next?" value={next} onChange={setNext} choices={['Compare my price and customer budgets.','Keep a buffer before I spend.','Try a different choice and compare results.']}/><button className="play-primary" disabled={why.length<3||next.length<3} onClick={()=>send('reflect',{changed:why,next})}>Keep my learning and continue</button></>;
    if(game.phase==='recovery')return recovery(game);
    if(game.phase==='settlement'||game.phase==='done')return <><div className="play-finish-coins"><span>Wallet <b>{game.wallet}</b></span><span>Saved <b>{game.savings}</b></span>{game.liability>0&&<span>Still owed <b>{game.liability}</b></span>}</div><p className="play-note">{game.reflections.length} laps reflected on · {game.events.filter(e=>e.type==='decision').length} business decisions recorded.</p>{game.phase==='settlement'?<><Reason label="What will I take into my next game?" value={why} onChange={setWhy} choices={['A good choice starts with checking costs.','I can learn from a choice that loses coins.','I can explain my plan and try again.']}/><button className="play-primary" disabled={why.length<3} onClick={()=>send('finish',{reason:why})}>Finish Money Quest</button></>:<><p className="play-feedback">{game.settlement}</p><button className="play-primary" onClick={restart}>Start a new practice</button></>}<button className="play-quiet" onClick={()=>setInfo('report')}>View parent learning report</button></>;
    return null;
  }
  if(!g)return <div className="quest-app play-welcome"><header><Brand/><a href="/">Back to home</a></header><main><div><span className="play-mini-label">YOUR CHOICES. YOUR LITTLE BUSINESS.</span><h1>A little stall.<br/>A lot to discover.</h1><p>Try a price. Meet your customers. Follow Sparko through a village of small business decisions.</p><div className="play-avatar-options">{mascots.map(m=><button key={m.id} aria-pressed={avatar===m.id} onClick={()=>setAvatar(m.id)} style={{borderColor:m.color}}>{m.name}</button>)}</div><label className="play-field">My journey<select value={length} onChange={e=>setLength(+e.target.value as 2|4)}><option value={4}>Four laps · the complete adventure</option><option value={2}>Two laps · shorter practice</option></select></label><label className="play-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Save my practice choices on this browser.</label><button className="play-primary" disabled={!consent} onClick={()=>{const seed=crypto.getRandomValues(new Uint32Array(1))[0];setGame(createMission(seed,length,avatar));setRoll(null);}}>Begin Money Quest <ArrowRight size={18}/></button><p className="play-note">Solo practice. No account or public chat. Use your ideas, not personal information.</p></div><div className="play-welcome-character"><CharacterPortrait name={avatar} animation="Idle"/></div></main></div>;
  if(info==='report')return <div className="quest-app play-parent-view"><header><Brand/><button className="play-primary" onClick={()=>setInfo('')}>Back to my board <X size={16}/></button></header><LearningReportView report={missionReport(g)}/></div>;
  return <div className="quest-app quest-play" data-reduced={reduced} data-quest-phase={g.phase}>
    <header className="play-header"><Brand/><div className="play-progress"><span>Q{g.quarter} · {quarterNames[g.quarter-1]}</span><div aria-label={`Space ${sample.tile} of 20`}>{Array.from({length:20},(_,i)=><i key={i} className={i<sample.tile?'past':i===sample.tile?'here':''}/>)}</div><small>Turn {g.turn + (g.phase === 'board' ? 1 : 0)} · Roll. Explore. Choose.</small></div><div className="play-balances" aria-label="Business balances"><span><Wallet/><small>Wallet</small><b key={g.wallet} data-testid="quest-wallet">{g.wallet}</b></span><span><PiggyBank/><small>Savings</small><b key={g.savings}>{g.savings}</b></span></div><details className="play-menu" ref={menu}><summary aria-label="Mission tools"><Menu/></summary><nav aria-label="Mission tools"><button onClick={()=>openInfo('report')}>Parent learning report</button><button onClick={()=>openInfo('ledger')}>My coin history</button><button onClick={()=>openInfo('word-bank')}>Word Bank</button><button onClick={()=>openInfo('lab')}>Try with practice coins</button><button onClick={toggleMotion}>Motion: {reduced?'reduced':'full'}</button><button aria-pressed={voice} onClick={()=>setVoice(!voice)}><Volume2 size={15}/> Voice {voice?'on':'off'}</button><a href="/">Back to home</a></nav></details></header>
    <main className="quest-layout quest-game-layout" data-phase={g.phase} data-quarter={g.quarter} data-busy={busy}>
      <section className="play-board-stage" aria-label="Your village game board"><div className="quest-scene play-board-world">{textBoard?<TextBoard position={sample.tile} onInspect={inspect}/>:<BoardWorld onReady={setReady} presentation={{...sample,value:dieValue,replacement:dieChance}} missionView={{id:g.id,avatar:g.avatar,game:{outcome:g.outcome}}} onInspectTile={inspect} highlightedTile={info==='guide'?inspected:['decision','outcome','reflection'].includes(g.phase)?g.position:null}/>}
      <div className="play-board-controls"><button aria-label={textBoard?'Show 3D board':'Use accessible text board'} onClick={()=>setTextBoard(!textBoard)}>{textBoard?'3D board':'Text board'}</button><button aria-label="Reset board view" title="Reset board view" onClick={()=>window.dispatchEvent(new Event('lead:reset-camera'))}><RotateCcw size={15}/></button><button onClick={()=>inspect(sample.tile)} disabled={busy}>Explore</button></div>
      <span className="play-location"><i/> {busy?'On the way':boardNames[sample.tile]}</span></div><footer className="play-stall-strip"><span><House size={17}/><b>Bento Box Co.</b></span><span>Price <b>{g.price}</b></span><span>Cost <b>{g.cost}</b></span><span className="play-margin">Margin <b>{g.price-g.cost}</b></span><span className="play-lap">Lap {g.quarter}/{g.quarters}</span></footer></section>
      <BoardConversation footer={!busy&&!info&&g.phase==='outcome'?<button className="play-primary" onClick={()=>send('continue')}>Next roll <ArrowRight size={16}/></button>:undefined} title={title} guide={guide} busy={busy} quarter={g.quarter} position={sample.tile} avatar={g.avatar} reduced={reduced} portrait={<CharacterPortrait name="sparko" animation={busy?'Encourage':g.phase==='outcome'?'Explain':'Talk'}/>}><div className="quest-panel play-chat-content" ref={panel} tabIndex={-1} aria-label="Current mission step">{error&&<p className="quest-error" role="alert">{error}</p>}{storageError&&<p className="quest-error" role="alert">Progress cannot be saved in this browser. Keep this page open.</p>}{!busy&&!info&&g.lastDie>0&&['decision','outcome','reflection'].includes(g.phase)&&<p className="play-roll-receipt" data-testid="mission-roll-result"><Dice5 size={17}/><span>Rolled <b>{g.lastDie}</b> · {boardNames[g.position]}{g.remaining>0&&<small>{g.remaining} steps saved for the next lap</small>}</span></p>}{!busy&&!info&&g.phase==='reflection'&&<div className="play-milestone" key={`lap-${g.quarter}`}><Flag/><strong>Lap {g.quarter} explored</strong><span>{g.quarter} / {g.quarters} village laps</span><i/><i/><i/></div>}{!busy&&!info&&g.phase==='outcome'&&(outcomeTotals?.finance.profit??g.outcome?.profit??0)>0&&<p className="play-success" key={`profit-${g.turn}`}><Sparkles size={17}/> Your stall earned {outcomeTotals?.finance.profit??g.outcome!.profit} coins profit!</p>}{!busy&&!info&&['board','decision','outcome'].includes(g.phase)&&investment&&<p className="play-feedback play-investment-result" role="status"><strong>Your stock result</strong><br/>{Number(investment.data.stake)} staked · {Number(investment.data.returned)} returned · {signed(Number(investment.data.net))} coin change.<br/>This chance result does not move your character.</p>}{content(g)}</div></BoardConversation>
    </main>
  </div>;
}
function TextBoard({position,onInspect}:{position:number;onInspect:(index:number)=>void}){return <ol className="quest-text-board play-text-board" aria-label="Twenty-space forward board">{boardNames.map((name,i)=>{const row=i<=5?6-i:i<=10?1:i<=15?i-9:6,col=i<=5?1:i<=10?i-4:i<=15?6:21-i;return <li key={i} style={{gridRow:row,gridColumn:col}} aria-current={i===position?'step':undefined}><button aria-label={`Explore space ${i}: ${name}`} onClick={()=>onInspect(i)}><b>{i}{i===position?' ●':''}</b><span>{name}</span></button></li>;})}<li className="quest-board-center">YATAI<br/>VILLAGE<small>Your choices lead the way</small></li></ol>;}
