import { FormEvent, useEffect, useRef, useState } from 'react';
import { applyAction, createMission, description, financialTotals, Mission, options, validSave, VERSION } from '../../packages/money-quest/engine';
import { depositCopy, goals, lessonBeats, quarterNames, wordBank } from '../../packages/money-quest/content';
import { boardNames, mascots } from '../../packages/curriculum';
import { BoardWorld, CharacterPortrait } from './World';
import { DIE_MS, RollEvent, sampleRoll } from './board-presentation';
import { useGame } from './store';
import './quest-mission.css';

const SAVE='lead-money-quest-v03-local';
function load():Mission|null {try {const value=JSON.parse(localStorage.getItem(SAVE)||'null');return validSave(value)?value:null;}catch{return null;}}
const id=()=>crypto.randomUUID();
function TextField({label,value,set,placeholder='Use your own words. Do not include personal information.'}:{label:string;value:string;set:(s:string)=>void;placeholder?:string}) {return <label className="quest-field">{label}<textarea required minLength={3} maxLength={500} value={value} onChange={e=>set(e.target.value)} placeholder={placeholder}/></label>;}
export default function QuestMission() {
  const [g,setGame]=useState<Mission|null>(load),[avatar,setAvatar]=useState('prena'),[length,setLength]=useState<2|4>(4),[consent,setConsent]=useState(false);
  const [error,setError]=useState(''),[storageError,setStorageError]=useState(false),[info,setInfo]=useState(''),[voice,setVoice]=useState(false),[speaking,setSpeaking]=useState(false);
  const reduced=useGame(s=>s.reduced),toggleMotion=useGame(s=>s.toggleMotion);
  const [textBoard,setTextBoard]=useState(false),[ready,setReady]=useState(false),[roll,setRoll]=useState<RollEvent|null>(null),[elapsed,setElapsed]=useState(0);
  const [why,setWhy]=useState(''),[next,setNext]=useState(''),[price,setPrice]=useState(6),[goal,setGoal]=useState(goals[3]),[readiness,setReadiness]=useState([false,false,false]);
  const [upgrade,setUpgrade]=useState(false),[helper,setHelper]=useState('none'),[save,setSave]=useState(0),[stock,setStock]=useState(0),[reinvest,setReinvest]=useState(false),[recoveryAnswer,setRecoveryAnswer]=useState<number|null>(null);
  const current=useRef(g),lock=useRef(false),panel=useRef<HTMLElement>(null);current.current=g;
  const sample=sampleRoll(roll,elapsed,g?.position||0,reduced||textBoard);
  const busy=!sample.complete;
  function dispatch(type:string,data:Record<string,unknown>={}) {
    if(lock.current||busy||!current.current)return;
    lock.current=true;
    try {
      const other=load();if(other&&other.id===current.current.id&&other.receipts.length>current.current.receipts.length){current.current=other;setGame(other);setError('This mission changed in another tab. Its latest progress has been restored; please review it before choosing.');return;}
      const old=current.current,result=applyAction(old,{id:id(),type,...data});
      if(result.animation!==old.animation){const resume=result.turn===old.turn;const event={id:String(result.animation),value:result.lastDie,from:old.position,path:result.path,replacement:false,started:performance.now()-(resume?DIE_MS:0)};setRoll(event);setElapsed(resume?DIE_MS:0);}
      else if(result.outcome?.die!==undefined&&result.outcome!==old.outcome){setRoll({id:id(),value:result.outcome.die,from:old.position,path:[],replacement:true,started:performance.now()});setElapsed(0);}
      current.current=result;setGame(result);setError('');
    }catch(e){setError((e as Error).message);}finally{lock.current=false;}
  }
  useEffect(()=>{if(!g)return;try{localStorage.setItem(SAVE,JSON.stringify(g));setStorageError(false);}catch{setStorageError(true);}},[g]);
  useEffect(()=>{if(!roll||reduced||textBoard)return;let frame:number;const tick=(now:number)=>{const t=now-roll.started;setElapsed(t);if(!sampleRoll(roll,t,g?.position||0).complete)frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[roll,reduced,textBoard]);
  useEffect(()=>{setWhy('');setNext('');setError('');setPrice(g?.price||6);setGoal(g?.goal||goals[3]);setUpgrade(false);setHelper(g?.helper.hired?(g.helper.benefit?'benefit':'helper'):'none');setReadiness([false,false,false]);setRecoveryAnswer(null);panel.current?.focus();},[g?.phase,g?.quarter]);
  useEffect(()=>()=>{if('speechSynthesis' in window)window.speechSynthesis.cancel();},[]);
  useEffect(()=>{if('speechSynthesis' in window)window.speechSynthesis.cancel();setSpeaking(false);},[g?.phase,g?.lesson.step]);
  useEffect(()=>{
    if(!info)return;
    const dialog=document.querySelector<HTMLElement>('.quest-dialog');
    const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab'||!dialog)return;const items=Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,textarea,select,[tabindex="0"]'));const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}};
    document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);panel.current?.focus();};
  },[info]);
  const speak=(text:string)=>{
    if(!('speechSynthesis' in window)){setError('This browser has no narration voice. All narration is shown as text.');return;}
    window.speechSynthesis.cancel();if(!voice)return;
    const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.92;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(u);
  };
  const openInfo=(which:string)=>{setInfo(which);dispatch('evidence',{panel:which});};
  const total=g?financialTotals(g):null;
  const start=()=>{if(!consent)return;const seed=crypto.getRandomValues(new Uint32Array(1))[0];setGame(createMission(seed,length,avatar));setRoll(null);};
  function submit(e:FormEvent,type:string,data:Record<string,unknown>={}) {e.preventDefault();dispatch(type,{reason:why,...data});}
  function priceField() {return <label className="quest-field">Menu price: {price} coins<input aria-label="Menu price" type="range" min={g?.phase==='lesson'?4:Math.max(4,(g?.price||6)-1)} max={g?.phase==='lesson'?8:Math.min(8,(g?.price||6)+1)} value={price} onChange={e=>setPrice(+e.target.value)}/></label>;}
  const narration=g?.phase==='lesson'?(()=>{const b=lessonBeats(g.quarter,g.lesson.depth)[g.lesson.step];return `${b.title}. ${b.text} ${b.example} ${b.question}`;})():g?.outcome?`${g.outcome.title}. ${g.outcome.text}`:g?description(g).join('. '):'';
  return <div className="quest-app" data-reduced={reduced}>
    <header className="quest-header"><a href="/" className="quest-brand"><span>✦</span> LEAD <small>MONEY QUEST</small></a><nav aria-label="Mission tools"><button onClick={toggleMotion}>Motion: {reduced?'reduced':'full'}</button><button aria-pressed={voice} onClick={()=>{if(voice&&'speechSynthesis' in window)window.speechSynthesis.cancel();setVoice(!voice);setSpeaking(false);}}>Voice {voice?'on':'off'}</button><a href="/">Back to home</a></nav></header>
    <div className="quest-notice">Local practice • progress saved in this browser only • no child account or research upload • English prototype</div>
    {storageError&&<p role="alert" className="quest-error">Browser storage is unavailable. Progress cannot survive a refresh.</p>}
    {!g?<main className="quest-welcome"><div><span className="quest-kicker">FOUR QUARTERS. YOUR OWN STORY.</span><h1>A little stall.<br/>A lot to discover.</h1><p>Learn a money idea, run your business through the lantern-lit festival, notice what happens, then try a new plan. Your choices matter; your speed does not.</p><div className="quest-journey">Learn → plan → roll → decide → reflect</div><div className="quest-avatar-options">{mascots.map(m=><button key={m.id} aria-pressed={avatar===m.id} onClick={()=>setAvatar(m.id)} style={{borderColor:m.color}}>{m.name}<small>{m.role}</small></button>)}</div><label className="quest-field">Mission length<select value={length} onChange={e=>setLength(+e.target.value as 2|4)}><option value={4}>Four quarters · complete Money Quest</option><option value={2}>Two quarters · shorter practice</option></select></label><label className="quest-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Save my practice choices on this browser. Avoid personal information on shared devices.</label><button className="quest-primary" disabled={!consent} onClick={start}>Begin Money Quest</button><p className="quest-fine">Approved Friend Sessions need verified parent/teacher connections and a working backend. This mode is solo; no public matching or chat.</p></div><div className="quest-welcome-character"><CharacterPortrait name={avatar} animation="Wave"/></div></main>:<>
      <section className="quest-progress" aria-label="Quarter progress">{quarterNames.slice(0,g.quarters).map((name,i)=><div key={name} className={i+1===g.quarter?'active':i+1<g.quarter?'complete':''}><b>{i+1<g.quarter?'✓':`Q${i+1}`}</b><span>{name}</span></div>)}</section>
      <section className="quest-hud" aria-label="Business balances"><div><small>WALLET</small><strong data-testid="quest-wallet">{g.wallet} <span>coins</span></strong></div><div><small>PROTECTED SAVINGS</small><strong>{g.savings}</strong></div><div><small>PRICE / COST</small><strong>{g.price} / {g.cost}</strong></div><div><small>OBLIGATIONS</small><strong>{g.liability}</strong></div><div><small>FESTIVAL</small><strong>{g.festival} / 6 <span>{g.festival>=6?'✦':''}</span></strong></div><button onClick={()=>openInfo('ledger')}>Open ledger</button><button onClick={()=>openInfo('word-bank')}>Word Bank</button></section>
      <main className="quest-layout" data-phase={g.phase} data-quarter={g.quarter} data-busy={busy}>
        <div className="quest-world-column">
          <div className="quest-scene">
            {g.phase==='lesson'?<CharacterPortrait name="sparko" animation={speaking?'Talk':g.lesson.answered?'Encourage':'Explain'}/>:textBoard?<TextBoard position={sample.tile}/>:<BoardWorld presentation={{...sample,value:roll?.value||g.lastDie,replacement:!!roll?.replacement}} onReady={setReady} missionView={{id:g.id,avatar:g.avatar,game:{outcome:g.outcome}}}/>}
            <span className="quest-world-badge">{g.phase==='lesson'?'SPARKO’S LEARNING LAB':`Q${g.quarter} · ${boardNames[sample.tile]}`}</span>
          </div>
          <div className="quest-world-controls"><button onClick={()=>setTextBoard(!textBoard)}>{textBoard?'Show Blender 3D board':'Use accessible text board'}</button><button onClick={()=>openInfo('sparko')}>Ask Sparko</button>{voice&&<button onClick={()=>speak(narration)}>{speaking?'Restart narration':'Read this aloud'}</button>}</div>
          <div className="quest-status"><span>Goal: {g.goal}</span><span>Inventory {g.inventory}</span><span>Ads +{g.ads}</span><span>Helper: {g.helper.hired?(g.helper.benefit||g.helper.trained?'protected':'hired'):'not hired'}</span><span>Hedge: {g.hedge?'held':'none'}</span><span>Growth: {g.upgrade?'active':'not bought'}</span></div>
          <p className="quest-fine">Coming later in Yatai Village. Complete Money Quest to strengthen your first business.</p>
        </div>
        <section className="quest-panel" ref={panel} tabIndex={-1} aria-label="Current mission step">
          {error&&<p role="alert" className="quest-error">{error}</p>}
          {busy?<div className="quest-moving" role="status"><span className="quest-die">{['⚀','⚁','⚂','⚃','⚄','⚅'][(roll?.value||1)-1]}</span><h2>{sample.rolling?'Rolling the die…':'Walking the route…'}</h2><p>{sample.rolling?'One result, one movement.':'Your choice opens when your pawn reaches its space.'}</p></div>:<>
          {g.phase==='lesson'&&(()=>{const beats=lessonBeats(g.quarter,g.lesson.depth),b=beats[g.lesson.step],last=g.lesson.step===beats.length-1;return <><span className="quest-kicker">QUARTER {g.quarter} · LEARN {g.lesson.step+1} / {beats.length}</span><h1>{b.title}</h1><p>{b.text}</p><div className="quest-example" key={`${g.quarter}-${g.lesson.step}`}><span>LET’S SEE IT</span><p>{b.example}</p><div className="quest-coins" aria-hidden="true">{[0,1,2,3,4,5].map(i=><i key={i} style={{animationDelay:`${i*.13}s`}}>●</i>)}</div></div><h3>{b.question}</h3><div className="quest-answers">{b.choices.map((c,i)=><button key={c} disabled={g.lesson.answered} onClick={()=>dispatch('answer',{answer:i})}>{c}</button>)}</div>{g.lesson.answered&&<><p className="quest-feedback" role="status">{g.lesson.feedback}</p>{last?<form onSubmit={e=>submit(e,'lesson-next',{price,goal,ready:readiness.every(Boolean)})}>{g.quarter===1&&<>{priceField()}<label className="quest-field">My business goal<select value={goal} onChange={e=>setGoal(e.target.value)}>{goals.map(s=><option key={s}>{s}</option>)}</select></label></>}{g.quarter===4&&<fieldset><legend>Three readiness questions</legend>{['I considered my goal.','I checked what I need for unexpected costs.','I considered whether I can accept a loss.'].map((t,i)=><label className="quest-check" key={t}><input type="checkbox" checked={readiness[i]} onChange={e=>setReadiness(readiness.map((v,j)=>j===i?e.target.checked:v))}/>{t}</label>)}</fieldset>}<TextField label={g.quarter===1?`My bento costs ${price} because…`:'What will I try with this idea?'} value={why} set={setWhy}/><button className="quest-primary">Complete this lesson</button></form>:<button className="quest-primary" onClick={()=>dispatch('lesson-next')}>Continue learning</button>}</>}</>;})()}
          {g.phase==='deposit'&&<><span className="quest-kicker">COMPLETION, NOT FIRST-TRY CORRECTNESS</span><h1>You earned five coins.</h1><div className="quest-award">+5</div><p>{depositCopy}</p><button className="quest-primary" onClick={()=>dispatch('deposit')}>Import my lesson coins</button></>}
          {g.phase==='banner'&&<><span className="quest-kicker">QUARTER {g.quarter}</span><h1>{quarterNames[g.quarter-1]}</h1><p>{['Set your price, meet customers, and watch revenue become profit. Town Hall is a free tour.','Tax starts at Town Hall. Eight banking and tax fortunes join the box. Product Growth is optional.','Six team fortunes join the box. Choose whether to hire and pay for a reliability benefit.','Six investment fortunes join the box. Choose your money paths, then finish your story.'][g.quarter-1]}</p><p className="quest-feedback">Your 5-coin lesson deposit is recorded. Start itself pays nothing.</p><button className="quest-primary" onClick={()=>dispatch('banner')}>{g.quarter===1?'Open the festival board':'Review quarter choices'}</button></>}
          {g.phase==='offers'&&<form onSubmit={e=>submit(e,'offers',{price,upgrade,helper,save,stock,reinvest})}><span className="quest-kicker">PLAN BEFORE THE LAP</span><h1>Your next-quarter plan</h1>{priceField()}{!g.upgrade&&<label className="quest-check"><input type="checkbox" checked={upgrade} onChange={e=>setUpgrade(e.target.checked)}/>Buy Product Growth · 5 coins · +1 effective customer budgets permanently</label>}{g.quarter>=3&&<label className="quest-field">Helper arrangement<select value={helper} onChange={e=>setHelper(e.target.value)}><option value="none">Continue without a helper</option><option value="helper">Hire · 1 wage per Sales Day worked</option><option value="benefit">Hire with benefit · {g.helper.benefit?'already paid':'2 coins once'} + wages</option></select></label>}{g.quarter===4&&<fieldset><legend>Money paths · allocate at most 5 coins</legend><label className="quest-field">Save<input type="number" min={0} max={5} value={save} onChange={e=>setSave(+e.target.value)}/></label><label className="quest-check"><input type="checkbox" checked={reinvest} onChange={e=>setReinvest(e.target.checked)}/>Reinvest · 3 coins · +1 effective budgets</label><label className="quest-field">Stock stake<input type="number" min={0} max={3} value={stock} onChange={e=>setStock(+e.target.value)}/></label><p>Stock: 5–6 doubles, 3–4 returns, 1–2 loses your stake. Savings cannot be risked.</p><p className="quest-fine">Squad Invest requires an approved Friend Session and is unavailable in solo practice.</p><strong>Total allocation: {save+stock+(reinvest?3:0)} / 5</strong></fieldset>}<TextField label="I chose this plan because…" value={why} set={setWhy}/><button className="quest-primary">Confirm my quarter plan</button><p className="quest-fine">{g.remaining?`${g.remaining} steps from your original roll remain. They will continue after this plan.`:'Your next turn begins at Start.'}</p></form>}
          {g.phase==='board'&&<><span className="quest-kicker">QUARTER {g.quarter} · TURN {g.turn+1}</span><h1>What will the village bring?</h1><p>Your business belongs to you. Roll once, follow the route, then decide with the information available.</p><div className="quest-die">{g.lastDie?['⚀','⚁','⚂','⚃','⚄','⚅'][g.lastDie-1]:'⚄'}</div>{g.wallet>0?<button className="quest-primary" disabled={!ready&&!textBoard} onClick={()=>dispatch('roll',{turn:g.turn})}>{ready||textBoard?'Roll the die':'Loading the 3D board…'}</button>:<Recovery g={g} why={why} setWhy={setWhy} answer={recoveryAnswer} setAnswer={setRecoveryAnswer} send={dispatch}/>}<p className="quest-fine">No coins for passing Start. No extra turn for a six. No time limit on choices.</p></>}
          {g.phase==='decision'&&<form onSubmit={e=>e.preventDefault()}><span className="quest-kicker">{g.pending==='fortune'?'OMIKUJI · PERSONAL FORTUNE':g.pending==='market'?'MARKET CHANGE · YOUR STRATEGY':'YOUR DECISION'}</span><h1>{description(g)[0]}</h1><p>{description(g)[1]}</p><TextField label="My reason" value={why} set={setWhy}/><div className="quest-answers">{options(g).map(o=><button type="button" key={o.id} disabled={o.disabled||why.trim().length<3} onClick={()=>dispatch('choose',{choice:o.id,reason:why})}>{o.label}{o.disabled?' · unavailable':''}</button>)}</div><p className="quest-fine">Your choice locks before customer budgets or chance results are revealed.</p></form>}
          {g.phase==='outcome'&&g.outcome&&<><span className="quest-kicker">NOTICE THE RESULT</span><h1>{g.outcome.title}</h1><p>{g.outcome.text}</p>{g.outcome.die&&<p>Chance die: <b>{g.outcome.die}</b> · this roll does not move your pawn.</p>}{g.outcome.budgets&&<div className="quest-customers">{g.outcome.budgets.map((b,i)=><div key={i} style={{animationDelay:`${i*.12}s`}}><span>☺</span><small>Budget {b}</small></div>)}</div>}{g.outcome.revenue!==undefined&&<div className="quest-money-sequence"><span>Revenue <b>+{g.outcome.revenue}</b></span><span>Production <b>−{g.outcome.cost}</b></span><span>Wage <b>−{g.outcome.wage||0}</b></span><span>Profit <b>{g.outcome.profit}</b></span></div>}{g.revision&&<form onSubmit={e=>submit(e,'revise',{price})}>{priceField()}<TextField label="Keep or revise—what did I notice?" value={why} set={setWhy}/><button>Record this price decision</button></form>}<button className="quest-primary" onClick={()=>dispatch('continue')}>Continue my lap</button></>}
          {g.phase==='reflection'&&<form onSubmit={e=>submit(e,'reflect',{changed:why,next})}><span className="quest-kicker">QUARTER {g.quarter} COMPLETE</span><h1>Pause at Start.</h1><p>{g.quarter<g.quarters?`Before your next lesson, notice what changed. ${g.remaining?`${g.remaining} rolled steps are safely held for the next quarter.`:''}`:'Your final lap is complete. Reflect before settling the mission.'}</p><TextField label="What changed this quarter?" value={why} set={setWhy}/><TextField label="What will I try next?" value={next} set={setNext}/><button className="quest-primary">Save my quarter reflection</button></form>}
          {g.phase==='recovery'&&<><h1>A plan, not an ending.</h1><Recovery g={g} why={why} setWhy={setWhy} answer={recoveryAnswer} setAnswer={setRecoveryAnswer} send={dispatch}/></>}
          {(g.phase==='settlement'||g.phase==='done')&&<><span className="quest-kicker">YOUR OWN HISTORY · NO RANKINGS</span><h1>{g.phase==='done'?'A founder who keeps learning.':'Look at your journey.'}</h1><p>{g.outcome?.text}</p><div className="quest-history">{g.reflections.map(r=><article key={r.quarter}><b>Q{r.quarter} · Wallet {r.wallet} · Savings {r.savings}</b><p>{r.changed}</p><small>Next: {r.next}</small></article>)}</div><p>Final wallet <b>{g.wallet}</b> · savings <b>{g.savings}</b> · still owed <b>{g.liability}</b></p><p>Business profit: <b>{total?.profit}</b>. Gifts, deposits, transfers, and advances are not sales revenue.</p>{g.fx.dream&&g.savings>=5&&<p className="quest-feedback">✦ Future-stall sign earned · cosmetic only</p>}{g.phase==='settlement'?<form onSubmit={e=>submit(e,'finish')}><TextField label="My decision, reason, result, and what I’ll keep or change next time" value={why} set={setWhy}/><button className="quest-primary">Finish Money Quest</button></form>:<><p className="quest-feedback">{g.settlement}</p><button className="quest-primary" onClick={()=>{setGame(null);setConsent(false);setRoll(null);localStorage.removeItem(SAVE);}}>Start a new practice</button></>}</>}
          </>}
        </section>
      </main>
      {info&&<div className="quest-overlay" onKeyDown={e=>{if(e.key==='Escape')setInfo('');}}><section role="dialog" aria-modal="true" aria-label={info==='ledger'?'Business ledger':info==='word-bank'?'Word Bank':'Ask Sparko'} className="quest-dialog"><button className="quest-close" autoFocus onClick={()=>setInfo('')}>Close</button><h2>{info==='ledger'?'Your business ledger':info==='word-bank'?'Word Bank':'A moment with Sparko'}</h2>{info==='word-bank'?<dl>{wordBank.map(([term,meaning])=><div key={term}><dt>{term}</dt><dd>{meaning}</dd></div>)}</dl>:info==='ledger'?<><p>Revenue {total?.revenue} · production {total?.cost} · wages {total?.wage} · other expenses {total?.expenses}</p><div className="quest-table"><table><thead><tr><th>Quarter / entry</th><th>Wallet Δ</th><th>Savings Δ</th><th>Owed Δ</th></tr></thead><tbody>{g.ledger.map(e=><tr key={e.id}><td>Q{e.quarter} · {e.note}</td><td>{e.wallet}</td><td>{e.savings}</td><td>{e.liability}</td></tr>)}</tbody></table></div><p className="quest-fine">Only on this browser. Seed {g.seed} · {VERSION}. Opening this panel is recorded as practice context, not a score.</p></>:<><div className="quest-small-portrait"><CharacterPortrait name="sparko" animation="Ask"/></div><p>What is your goal? What changed in your wallet, costs, or customer budgets? Which information would help you decide?</p><p>I can explain a word, but the choice and your reason belong to you.</p></>}</section></div>}
    </>}
  </div>;
}
function Recovery({g,why,setWhy,answer,setAnswer,send}:{g:Mission;why:string;setWhy:(s:string)=>void;answer:number|null;setAnswer:(n:number)=>void;send:(t:string,d?:Record<string,unknown>)=>void}) {const b=lessonBeats(g.quarter,'review')[0];return <div className="quest-recovery"><p>Your wallet is empty. You are not eliminated. Savings stay protected.</p><TextField label="My recovery plan and reason" value={why} set={setWhy}/><button disabled={why.trim().length<3} onClick={()=>send('recover',{choice:'advance',reason:why})}>Take 5-coin advance · repay at Goal</button><h3>Or learn and reflect for 3 coins</h3><p>{b.question}</p>{b.choices.map((c,i)=><button key={c} aria-pressed={answer===i} onClick={()=>setAnswer(i)}>{c}</button>)}{answer!==null&&<p className="quest-feedback">{b.explanation}</p>}<button disabled={answer===null||why.trim().length<3} onClick={()=>send('recover',{choice:'learning',answer,reason:why})}>Complete learning recovery</button></div>;}
function TextBoard({position}:{position:number}) {return <ol className="quest-text-board" aria-label="Twenty-space clockwise board">{boardNames.map((name,i)=>{const row=i<=5?6-i:i<=10?1:i<=15?i-9:6;const col=i<=5?1:i<=10?i-4:i<=15?6:21-i;return <li key={i} style={{gridRow:row,gridColumn:col}} aria-current={i===position?'step':undefined}><b>{String(i).padStart(2,'0')}{i===position?' ●':''}</b><span>{name}</span></li>;})}<li className="quest-board-center">YATAI<br/>FESTIVAL<br/><small>Clockwise ↑ → ↓ ←</small></li></ol>;}
