// Gameplay specification: LEAD Money Quest Developer Handoff v0.3.
// Lesson prose is an original prototype adaptation, not a transcription of the textbook.
export type Depth = 'core' | 'deeper' | 'review';
export const quarterNames = ['Open for business', 'The village notices you', 'Your first teammate', 'Money paths'];
export const depositCopy = 'You earned these LEAD Coins from your lesson. Now use them to run your business this quarter.';
export const goals = ['Keep customers', 'Protect profit', 'Grow the business', 'Balance customers and profit'];
export const customerBudgets = [4,4,5,5,6,6,6,7,7,8,8,10];
export const wordBank = [
  ['Price', 'What one customer pays for one bento. Your normal menu price is 4–8 coins.'],
  ['Revenue', 'All money customers pay for successful sales, before any costs leave.'],
  ['Production cost', 'Ingredients and packaging for each bento sold. Normally 3 coins. No sale means no production cost.'],
  ['Profit', 'Revenue minus production costs, wages, refunds, and other business expenses. Transfers and loans are not profit.'],
  ['Break-even / cost recovery', 'Revenue exactly covers costs. Nothing is gained or lost.'],
  ['Loss', 'Costs are greater than revenue. Notice what changed and consider your next step.'],
  ['Tax / sales tax', 'Money that supports shared services. This game uses a simplified wallet levy: round 10% of wallet up at Town Hall from Q2. It is not a simulation of Japanese consumption tax.'],
  ['Refund / return payment', 'Money returned to a customer after a sale. The original production cost still happened.'],
  ['Savings', 'Your own coins set aside. Ordinary events cannot spend them. Moving money to savings does not create profit.'],
  ['Wage', 'Pay for work. A hired helper earns 1 coin on each Sales Day they work, even when visitors do not buy.'],
  ['Benefit', 'A 2-coin reliability arrangement for your helper. In this game it prevents absence; it is not a real employment policy.'],
  ['Interest', 'An extra payment for saving or borrowing. A neighbour loan gives 3 now but requires 4 back.'],
  ['Liability', 'An amount still owed. An advance increases both your wallet and what you must repay.'],
  ['Investment', 'Using money now for a possible future return. A return is not guaranteed.'],
  ['Risk', 'Uncertainty about what will happen and how much you might lose.'],
  ['Reinvest', 'Spend on your own business. Here, 3 coins improves effective customer budgets by 1.'],
  ['Inventory token', 'A prepaid ingredient token. One token replaces the production cost of one successful sale.'],
  ['Insurance / hedge', 'Paying a known small amount to protect against a specific future setback. Read what it covers.'],
  ['Advertising', 'An invitation to more visitors, not a promise that their budgets meet your price.'],
  ['Evidence', 'Information you actually looked at, such as previous budgets, costs, or a result.'],
];
export type Beat = { title: string; text: string; example: string; question: string; choices: string[]; answer: number; explanation: string };
const beat = (title:string,text:string,example:string,question:string,choices:string[],answer:number,explanation:string):Beat => ({title,text,example,question,choices,answer,explanation});
const core: Beat[][] = [
  [beat('Set a smart price','Price is what a customer pays. Cost is what your business spends making a sold bento. The difference is profit. Compare a simple market bento at 5 coins and a premium one at 7. Neither price is always best.','At price 6 and cost 3: 6 comes in → 3 leaves → 3 remains.','Which amount is profit?',['6 coins','3 coins','9 coins'],1,'The 6 is revenue. After paying the 3-coin cost, 3 remains.'),
   beat('Customers have different budgets','A visitor can buy when their budget meets your effective price. You make bentos to order, so a visitor who cannot buy creates no production cost.','Budgets 5, 6, 8 at price 6: 2 sales; revenue 12; cost 6; profit 6. At price 5: 3 sales; revenue 15; cost 9; profit 6.','What does this comparison show?',['Lower price always gives more profit','Different choices can give equal profit','Every visitor must buy'],1,'Both prices earn 6 profit, but one serves more customers. Your goal helps you choose.'),
   beat('Give your price a reason','A thoughtful choice connects your goal with what you noticed. You can keep a price after reviewing evidence. Revision does not always mean changing it.','My bento costs 6 because I want to balance affordability and the cost of fresh ingredients.','What belongs in a useful reason?',['Only the colour of my pawn','A promise that everyone will buy','My goal and information I noticed'],2,'Use a goal, cost, or customer evidence. Your reason is yours; Sparko does not choose it.')],
  [beat('Protect some savings','From Quarter 2, Town Hall collects a simplified tax of 10% of your wallet rounded up. Savings are excluded and protected from negative events.','Wallet 11 → tax 2. Save 3 first: wallet 8, savings 3 → tax 1. The transfer itself earns nothing.','Wallet 8 and savings 3: what is the Town Hall tax?',['1 coin','3 coins','0 coins'],0,'10% of 8 is 0.8, rounded up to 1. Savings are not included.'),
   beat('A fair return','A refund returns the selling price. A replacement first costs the current production cost; a roll of 4–6 works, while 1–3 also requires a refund. No prior sale means a story moment, not a charge.','A 6-coin refund costs 6. A 3-coin replacement costs 3 if successful, or 9 if it also needs that refund.','Which is certain before choosing?',['A replacement will work','The full refund amount','Replacement is always cheaper'],1,'A known refund and an uncertain replacement are different risks. Explain your own choice.'),
   beat('Recover your costs','Break-even means revenue equals cost. A refund or fee can turn an earlier profit into a loss. Review the whole ledger, not only the latest money coming in.','Revenue 6 − production 3 − a 3-coin fee = 0: break-even.','What is break-even?',['The largest wallet','Revenue equals costs','No customers visited'],1,'Cost recovery means you have covered what you spent, without a profit or loss.')],
  [beat('Your first teammate','A helper serves one extra customer on Sales Days. They earn a wage of 1 coin each Sales Day they work, even if customers cannot buy. Hiring is optional.','Two sales at 6: revenue 12 → production 6 → wage 1 → profit 5.','Why separate wage from revenue?',['Wage is another cost','Wage is free income','Wage guarantees sales'],0,'Work has a cost. More visitors are an opportunity, not a guaranteed return.'),
   beat('Pay for reliability','Without a benefit, a movement roll of 1 on a Sales Day means the helper is absent: no extra customer and no wage. The 2-coin benefit prevents absence.','Pay 2 once for the benefit, then pay the normal 1-coin wage on days worked.','What does the benefit buy?',['Free wages forever','Guaranteed customer purchases','Reliable attendance'],2,'The benefit prevents absence. It does not remove wages or guarantee sales.'),
   beat('Make a hiring plan','Look at your available wallet, likely customers, and your goal. You may hire with a benefit, hire without it, or continue alone. Each needs a reason, not a label.','A helper who works on 3 Sales Days earns 3 in wages. With the benefit, total helper spending is 5.','Three working days plus benefit cost?',['2 coins','5 coins','3 coins'],1,'Three wages plus the one-time 2-coin benefit totals 5.')],
  [beat('Choose your money path','First ask: What is my goal? Can I still cover an unexpected cost? Can I accept losing what I risk? Placing zero is a valid choice.','You can allocate up to 5 wallet coins. Protected savings can never be staked.','Which money can be used for a stock stake?',['Protected savings','Another child’s coins','Only available wallet coins'],2,'Only risk your own available wallet money, never protected savings.'),
   beat('Compare the paths','Save preserves coins and earns 1 interest at Goal if savings reach 3. Reinvest costs 3 and adds 1 to effective budgets. Stock risks up to 3: 5–6 doubles the stake, 3–4 returns it, 1–2 loses it. Squad Invest belongs only in approved Friend Sessions.','Stake 2: receive 4, 2, or 0. Those are returns of the stake; profit is +2, 0, or −2.','A returned 2-coin stake means?',['2 new profit','Break-even on the investment','A guaranteed future win'],1,'Your original 2 came back. You did not earn 2 new coins.'),
   beat('Explain and review','Name your path, connect it to a goal, and say what you would do if it goes differently. The richest result does not prove the most thoughtful decision.','I chose Save because I want a buffer. Next time I will compare that buffer with my business costs.','What should you review after a risky choice?',['Only whether I won','How fast I clicked','My reason, result, and next plan'],2,'Luck and learning are separate. Describe what happened without turning it into a permanent label.')],
];
const deeper = [
 beat('Compare margins, not just sales','A margin is the difference between the selling price and per-bento cost. Higher margins can come with fewer customers.','Price 7, cost 3: margin 4. Two sales produce 8 profit. Price 5: margin 2; four sales also produce 8.','How many sales at a margin of 2 produce 8?',['2','4','8'],1,'4 × 2 = 8. Customer count and margin work together.'),
 beat('Borrowing has a repayment cost','The neighbour offer gives 3 now and requires 4 at the next Town Hall. The extra 1 is interest. Borrowing is not sales income.','Wallet rises by 3, but the obligation is 4. Saving those 3 does not erase the obligation.','What is the borrowing cost?',['4 coins','3 coins','1 coin'],2,'Repayment 4 minus borrowed principal 3 equals 1 interest.'),
 beat('Plan payroll across a quarter','Reliability changes the chance of attendance, not affordability. Compare the guaranteed benefit cost with the extra opportunities and your buffer.','At price 4, cost 3, two successful sales and wage 1 leave 1 profit. With no sales, the wage still costs 1.','If no visitors buy and the helper works, what is the result?',['1-coin loss','No cost','1-coin profit'],0,'No production cost is charged, but the 1-coin wage still leaves a loss.'),
 beat('Risk has several possible outcomes','Equal possible die faces do not make a win certain. Compare all outcomes before committing and keep enough money for costs.','A 3-coin stake returns 6 on two faces, 3 on two faces, and 0 on two faces. The range of net results is −3 to +3.','Can one lucky stock win measure adaptability?',['Yes','No','Only on a six'],1,'The result includes chance. Evidence is what you considered, chose, and learned.'),
];
export function lessonBeats(quarter:number, depth:Depth):Beat[] {
  const list = core[quarter-1];
  if(depth === 'review') return [{...list[0], title: 'A quick refresh: '+list[0].title}, list[2]];
  return depth === 'deeper' ? [...list,deeper[quarter-1]] : list;
}
export const markets = [
 ['Rice Price Shock','Production cost rises by 1. Raise price by 1, keep your price, or pay 3 to search; a 4–6 restores the old cost.'],
 ['Cheaper Competitor','A neighbour prices one coin lower. Reduce your price, defend your value (next budgets −1), or spend 2 on a promotion.'],
 ['Rainy Festival','Stay open for one customer, pay 2 for delivery and two customers, or close with no sale and no cost.'],
 ['Packaging Shortage','Pay 3 for emergency boxes, use plain packaging (next budget −1), or skip the next sale.'],
 ['Customer Trend','Pay 2 for a healthier recipe (+1 budgets for three customers), keep your product, or discount the next sale by 1.'],
 ['Large Order','Accept three sales at a 1-coin discount, decline, or counteroffer two at normal price (4–6 accepts).'],
 ['Equipment Breakdown','Pay 4 to repair, pay 2 for a temporary repair (1–3 also requires 4 next turn), or close one Sales Day.'],
 ['Community Event','Give two inventory tokens or 2 coins for +1 next budget, sell to two visitors, or decline.'],
];
export const fortunes = [
 ['Great blessing','positive','Next Sales Day draws 2 extra customers.'],['Tip jar','positive','A grateful customer leaves 1 coin.'],['Festival rush','positive','One extra customer visits now at your normal price.'],['Clean stall award','positive','Your clean stall earns a 1-coin award.'],['Recipe compliment','positive','Your next customer’s effective budget is 1 higher.'],['Cash box recount','positive','You find a missed coin: +1, not new sales revenue.'],
 ['Dropped tray','negative','A tray needs a 1-coin repair.'],['Spoiled rice','negative','Use one inventory token, or pay 1 if none remain.'],['Torn banner','negative','Repair your banner for 1 coin.'],['Smudged price sign','negative','Your next sales opportunity uses a price 1 lower.'],['Order mix-up','negative','Return 1 coin to a customer.'],['Drizzle','negative','Next Sales Day, effective customer budgets are 1 lower.'],
 ['Bulk rice offer','choice','Pay 4 for 3 inventory tokens, or decline.'],['Fancy packaging','choice','Pay 2 for +1 budget for your next 2 customers, or decline.'],['Secondhand griddle','choice','Pay 3 and roll: 4–6 gives +1 budgets for 3 customers; 1–3 gives no improvement. Or decline.'],['Charity bento','choice','Give one inventory token or 2 coins for Festival +2 and next budget +1. Or decline.'],['Save-it slip','choice','Move 0–2 wallet coins to savings, or decline.'],['Taste-test day','choice','Pay 1: next Big Sale budgets +1. Or decline.'],['Kitchen trade','choice','Swap one inventory token for 2 wallet coins, or decline.'],['Tie it to the tree','choice','Keep a hedge that can cancel one future negative fortune for 1 coin, or decline.'],
 ['Neat ledger refund','positive','Your records earn a 1-coin tax refund.'],['Interest day','positive','If savings are at least 3, add 1 directly to savings.'],['Account fee','negative','Pay a 1-coin account fee from your wallet.'],['Late filing notice','negative','Your next Town Hall tax has a 1-coin extra fee.'],['Early tax payment','choice','Pay 1 now to skip your next Town Hall tax, or decline.'],['Neighbour loan','choice','Borrow 3 now and repay 4 at your next Town Hall, or decline.'],['Rain insurance','choice','Pay 1 to ignore the next Rainy Festival this quarter, or decline.'],['Pay-tomorrow regular','choice','Accept an extra full-price order next Sales Day. On a movement roll of 1 they do not pay. Or decline.'],
 ['Sick day','negative','Without a benefit or training, your hired helper misses the next Sales Day.'],['Payroll mix-up','negative','With a helper hired, pay 1 extra wage.'],['Helper’s idea','choice','With a helper, pay 2 for +1 budgets for the rest of this quarter. Or decline.'],['Bonus request','choice','Pay 1: your hired helper serves 1 extra customer next Sales Day. Or decline.'],['Training course','choice','Pay 2: your helper cannot be absent and serves +1 on Big Sales. Or decline.'],['Teamwork','positive','With a hired helper, your next Big Sale starts with 4 visitors instead of 3.'],
 ['Second-stall dream','choice','Set a savings goal of 5. Reach it at Goal to earn a cosmetic future-stall sign. Or decline.'],['Investor visitor','choice','Take 3 now; pay 1 at each remaining Town Hall. Or decline.'],['Market rumour','choice','Pay 1 to preview the next Market Change, or decline.'],['Stock tip','choice','Stake up to 2 wallet coins: 5–6 doubles, 3–4 returns, 1–2 loses the stake. Or decline.'],['Give back','choice','Donate 2: Festival +3 and budgets +1 next Sales Day. Or decline.'],['Grand fortune','positive','Choose +2 wallet coins, +1 inventory token, or Festival +3.'],
] as const;
export const layerSize = (q:number) => [20,28,34,40][q-1];
